# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  ## Workspaces
  workspace: &workspace
    ~/repo

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      ##_JAVA_OPTIONS: '-Xms512m -Xmx3072m'
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms1024m -Xmx3072m -XX:MaxMetaspaceSize=1536m"
      ## GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m" -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false -DdisablePreDex'

  ## Cache
  gradle_key: &gradle_key
    jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "ui/build.gradle" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Dependencies
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies


jobs:
  build:
    <<: *android_config
    steps:
      - checkout

      - *restore_gradle_cache

      ##- run:
      ##    name: Print available emulator images
      ##    command: sdkmanager --list --verbose | grep system-images

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-28;google_apis_playstore;x86_64" && echo "no" | avdmanager create avd -n test -k "system-images;android-28;google_apis_playstore;x86_64"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true

      - *android_dependencies
      - *save_gradle_cache

      ##- run:
      ##    name: Pre-check
      ##    command: ./gradlew ktlint lint

      ##- run:
      ##    name: Run Unit Tests
      ##    command: ./gradlew testDebugUnitTest

      - run:
          name: Run Instrumented Tests
          command: ./gradlew connectedDebugAndroidTest

      ##- store_artifacts:
      ##    path: app/build/reports
      ##    destination: reports

      ##- store_test_results:
      ##    path: app/build/test-results