# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  ## Workspaces
  workspace: &workspace
    ~/repo

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx1g -Xms1g"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1g" -Dorg.gradle.daemon=false -Dkotlin.incremental=false -DdisablePreDex'

  ## Cache
  gradle_key: &gradle_key
    jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "ui/build.gradle" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Dependencies
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  ## Emulator
  setup_emulator: &setup_emulator
    run:
      name: Setup emulator
      command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"

  launch_emulator: &launch_emulator
    run:
      name: Launch emulator
      command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
      background: true

  ## Prints
  print_emulator_images: &print_emulator_images
    run:
      name: Print available emulator images
      command: sdkmanager --list --verbose | grep system-images

  ## Checks
  checka: &check
    run:
      name: Pre-check
      command: ./gradlew ktlint lint --stacktrace

  ## Tests
  ## https://github.com/objectbox/objectbox-java/issues/555
  unit_test: &unit_test
    run:
      name: Run Unit Tests
      command: ./gradlew testDebugUnitTest -x transformClassesWithObjectBoxAndroidTransformForDebug

  integration_tests_ui: &integration_tests_ui
    run:
      name: Run Instrumented Ui Tests
      command: ./gradlew :ui:connectedDebugAndroidTest --no-daemon -Pkotlin.incremental=false --max-workers=2

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      ## - *print_emulator_images

      - *restore_gradle_cache

      ##- *setup_emulator
      ##- *launch_emulator

      - *android_dependencies

      - *save_gradle_cache

      - run:
          name: Add google-services
          command: echo $GOOGLE_SERVICES | base64 --decode > ~/repo/ui/google-services.json

      - *check

      - *unit_test

      ##- run:
      ##    name: Run assemble
      ##    command: ./gradlew :ui:assembleAndroidTest --no-daemon -Pkotlin.incremental=false --max-workers=2

      ##- *integration_tests_ui

      - store_artifacts:
          path: ui/build/reports
          destination: reports

      - store_test_results:
          path: ui/build/test-results